# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              The Ugly Loaf
email:              theuglyloaf@protonmail.com
description:        Minimal Blog & Magazine Jekyll Theme
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://theuglyloaf.com' # The base hostname & protocol for your site
github_username:    weremoose
twitter_username:   aspirethemes
instagram_username: aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  amelekou:
    name:             Anastasia Melekou
    bio:              An enthusiastic breaker, mender and maker of things. I love baking bread but truth be told... most of the time, it does not turn out quite as expected!
    gravatar:         https://en.gravatar.com/userimage/38781779/0bbdddd45be4fe817db83891fe96319f.jpg?size=200
    email:            theuglyloaf@protonmail.com
    website:          https://melekou.com
    github_username:  weremoose
    twitter_username: ahmadajmi
